# Generated by Django 6.0.1 on 2026-01-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_order_to_aboutgalleryimage'),
    ]

    operations = [
        # Fields already exist from migration 0003, so nothing to do
    ]
