# Generated by Django 6.0.1 on 2026-01-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutsection_image_aboutsection_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
