# Generated by Django 6.0.1 on 2026-01-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutsection_image_aboutsection_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutgalleryimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
