# Generated by Django 6.0.1 on 2026-01-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutgalleryimage_image_blob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutgalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutgalleryimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='photo_url',
        ),
    ]
