# Generated by Django 6.0.1 on 2026-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_aboutgalleryimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('profil', models.CharField(help_text='Ex: Chercheur, Étudiant, Professionnel', max_length=100)),
                ('organisation', models.CharField(blank=True, max_length=100)),
                ('domaine', models.CharField(help_text="Votre domaine d'expertise", max_length=100)),
                ('motivation', models.TextField(help_text="Pourquoi souhaitez-vous rejoindre l'association?")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Membership Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
