# Generated by Django 6.0.1 on 2026-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_membershiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='niveau',
            field=models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], default='licence', max_length=20),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='niveau_autre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='pays',
            field=models.CharField(choices=[('senegal', 'Sénégal'), ('france', 'France'), ('cote_divoire', "Côte d'Ivoire"), ('maroc', 'Maroc'), ('tunisie', 'Tunisie'), ('autre', 'Autre')], default='senegal', max_length=50),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='pays_autre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
