# Generated by Django 6.0.1 on 2026-02-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_membershiprequest_niveau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiprequest',
            name='pays',
            field=models.CharField(choices=[('benin', 'Bénin'), ('senegal', 'Sénégal'), ('france', 'France'), ('cotedivoire', "Côte d'Ivoire"), ('maroc', 'Maroc'), ('tunisie', 'Tunisie'), ('algerie', 'Algérie'), ('mali', 'Mali'), ('burkina', 'Burkina Faso'), ('nigeria', 'Nigeria'), ('ghana', 'Ghana'), ('cameroon', 'Cameroun'), ('kenya', 'Kenya'), ('uganda', 'Ouganda'), ('rwanda', 'Rwanda'), ('south_africa', 'South Africa'), ('egypt', 'Egypt'), ('ethiopia', 'Ethiopia'), ('tanzania', 'Tanzania'), ('angola', 'Angola'), ('morocco', 'Morocco'), ('tunisia', 'Tunisia'), ('libya', 'Libya'), ('mauritius', 'Mauritius'), ('albania', 'Albania'), ('germany', 'Germany'), ('spain', 'Spain'), ('italy', 'Italy'), ('portugal', 'Portugal'), ('uk', 'United Kingdom'), ('ireland', 'Ireland'), ('belgium', 'Belgium'), ('netherlands', 'Netherlands'), ('switzerland', 'Switzerland'), ('austria', 'Austria'), ('poland', 'Poland'), ('czech', 'Czech Republic'), ('hungary', 'Hungary'), ('romania', 'Romania'), ('usa', 'United States'), ('canada', 'Canada'), ('mexico', 'Mexico'), ('brazil', 'Brazil'), ('argentina', 'Argentina'), ('chile', 'Chile'), ('colombia', 'Colombia'), ('venezuela', 'Venezuela'), ('peru', 'Peru'), ('australia', 'Australia'), ('new_zealand', 'New Zealand'), ('japan', 'Japan'), ('china', 'China'), ('india', 'India'), ('pakistan', 'Pakistan'), ('bangladesh', 'Bangladesh'), ('indonesia', 'Indonesia'), ('philippines', 'Philippines'), ('vietnam', 'Vietnam'), ('south_korea', 'South Korea'), ('north_korea', 'North Korea'), ('saudi_arabia', 'Saudi Arabia'), ('turkey', 'Turkey'), ('iran', 'Iran'), ('israel', 'Israel'), ('uae', 'United Arab Emirates'), ('qatar', 'Qatar'), ('kuwait', 'Kuwait'), ('oman', 'Oman'), ('bahrain', 'Bahrain'), ('south_africa2', 'South Africa'), ('nigeria2', 'Nigeria'), ('ghana2', 'Ghana'), ('autre', 'Autre')], default='benin', max_length=50),
        ),
    ]
